unstable_features = true
brace_style = "AlwaysNextLine"
combine_control_expr = false
comment_width = 120
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
edition = "2018"
empty_item_single_line = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Always"
single_line_if_else_max_width = 0
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = false
wrap_comments = true
